version: '3'

services:
  app:
    container_name: nestjs_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - docker.env
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - docker.env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: